### ISSUE TITLE
Future request: Hide scale

### ISSUE THREAD

**Issue by fatuuse** [kandsten/ha-heatmap-card#14]
To have a minimized row with only 1-2 days I would like to have a heatmap without scale. Is it possible to add a setting like ?
```
scale:
  show: false
```

**Comment by koddistortion** [comment]
Do you mean the legend below the Heatmap?

What seems to be working is setting the display legend option to false via yaml:
```yaml
type: custom:heatmap-card
title:
entity: sensor.eg_temperatur
data:
  min: 17
  max: 20
days: 21
device_class: temperature
display:
  legend: false
scale:
  type: relative
  steps:
    - color: "#0f3489"
    - color: "#a9aee3"
    - color: "#e1e1e9"
    - color: "#f5f5f5"
    - color: "#f5f5f5"
    - color: "#f3dbd6"
    - color: "#ea755a"
    - color: "#cf0000"
```

resulting in this:

<img width="484" alt="image" src="https://github.com/user-attachments/assets/5499a587-2f00-4fbd-b750-824bb44a9e08">
