### ISSUE TITLE
Sun power

### ISSUE THREAD

**Issue by fatuuse** [kandsten/ha-heatmap-card#6]
I can't get it to work. Any hint?

```
title: Solcell
type: custom:heatmap-card
entity: sensor.sems_output_w
```
```
- platform: template
  sensors:
    sems_output_w:
      value_template: "{{ state_attr('sensor.inverter_grid_tied_pv_inverter','outputpower') | float(0) }}"
      unit_of_measurement: 'W'
      friendly_name: "Solcell effekt"
      icon_template: "mdi:meter-electric"
      device_class: power
```

In card conf: `Error: This entity is not a sensor. Only sensors are supported currently.`

Should I use any of:
```
device_class: power
state_class: power
```
